# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: easy_oj
  username: root
  password: admin
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: easy_oj
  username: easy_oj
  password: easy_oj
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: easy_oj
  username: easy_oj
  password: easy_oj
  socket: /tmp/mysql.sock
